### ISSUE TITLE
ENOENT: no such file or directory, open 'portal-cache/full-filter-cache.json'

### ISSUE THREAD

**Issue by ccsmart** [gawati/gawati-portal-server#3] opened 2018-03-20 12:13 UTC
Mar 20 13:09:00 alldev node: success: created smart filter cache
Mar 20 13:09:00 alldev node: error: file does not exist Error: ENOENT: no such file or directory, open 'portal-cache/full-filter-cache.json'
Mar 20 13:09:00 alldev node: responseFetchRecent
Mar 20 13:09:00 alldev node: success: created cache portal-cache/recent-docs.json
Mar 20 13:09:00 alldev node: success: created smart filter cache
Mar 20 13:10:00 alldev node: success: created smart filter cache
Mar 20 13:10:00 alldev node: error: file does not exist Error: ENOENT: no such file or directory, open 'portal-cache/full-filter-cache.json'
Mar 20 13:10:00 alldev node: success: created smart filter cache
Mar 20 13:11:00 alldev node: success: created smart filter cache
Mar 20 13:11:00 alldev node: success: created smart filter cache
Mar 20 13:11:00 alldev node: error: file does not exist Error: ENOENT: no such file or directory, open 'portal-cache/full-filter-cache.json'

**Comment by kohsah** [comment] 2018-03-20 13:37
I believe this was fixed in https://github.com/gawati/gawati-portal-server/commit/af7351c10bd83c8a442771f888b8ddac68e90cd3 

Set package version to 1.0.9

**Comment by kohsah** [comment] 2018-03-20 13:38
Duplicate of Issue #2

**Closed as completed** 2018-04-03 07:00 UTC
